version: '3'
services:
  mongo:
    image: 'mongo:latest'
    ports:
        - 27017:27017
    volumes:
        - mongodb_data_container:/data/db
  app:
    container_name: julius-app-api
    restart: always
    build: .
    ports:
        - "3000:3000"
    depends_on:
        - mongo

volumes:
  mongodb_data_container: